import type { Metadata } from "next";

import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";

import { Nunito, Noto_Sans } from "next/font/google";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

const inter = Noto_Sans({
	subsets: ["latin"],
	weight: "400",
});
export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<ClerkProvider>
			<html lang="en">
				<body className={inter.className}>{children}</body>
			</html>
		</ClerkProvider>
	);
}
